services:
  db:
    image: postgres:16-alpine
    container_name: persona-db
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: persona_db
    ports:
      - "5432:5432"